### ISSUE TITLE
Generated plots should show parameter limits

### ISSUE THREAD

**Issue by hpretl** [efabless/cace#111]
Often it is really useful to have parameter limits in generated data plots. This allows an easy check if and with how much margin curves are inside or outside limits. Since all the information is in the YAML datasheet, this should be possible.

**Comment by hpretl** [comment]
@mole99 @RTimothyEdwards What do you think about this feature?

**Comment by mole99** [comment]
That sounds like a good idea! A dashed [`axhline`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axhline.html) could be used for xyplots to mark the limits.

**Comment by hpretl** [comment]
Sounds good! Looking forward to the next version(s) will all the great enhancements we have been discussing. :-)

**Comment by mole99** [comment]
Me too, now they just have to get implemented 😉

**Comment by mole99** [comment]
It seems the implementation isn't that simple ^^

|                    |                    |                    |
|--------------------|--------------------|--------------------|
|  ![gain_vs_temp](https://github.com/user-attachments/assets/23dde155-de30-499d-861c-5c7b57ba1b19)                  | ![ugf_vs_corner](https://github.com/user-attachments/assets/816c1950-88fc-4680-a478-8c66cc10a97a)                  |         ![pm_vs_vdd](https://github.com/user-attachments/assets/409891c6-74a6-4671-b766-2464dd3f7f06)           | 

If the limits are drawn unconditionally, then for some plots the axis is scaled in such a way that you can no longer see the values properly.

The solution I've come up with is to take the yrange (distance between min/max yvalue) and check if the limit that should be drawn is within that range. With a bit of a margin, that seems to work well:

|                    |                    |                    |
|--------------------|--------------------|--------------------|
|      ![gain_vs_temp](https://github.com/user-attachments/assets/55b52189-a67f-4a62-8432-01efff601c6c)            |         ![ugf_vs_corner](https://github.com/user-attachments/assets/77616b96-03c6-407c-8566-0847b5b58864)           |               ![pm_vs_vdd](https://github.com/user-attachments/assets/4e4ca2eb-9294-4f6c-b0af-229a4510e254)     |

Only the first plot shows the limit, as it is close enough to the data points. If any of the lines would intersect the limit, it would always be shown as it lies inside the yrange.

**Comment by mole99** [comment]
Alright, then I would suggest the following setting for the `plot` entries in the datasheet:

- `limits`
  - `false` - do not show limits
  - `true` - always show limits
  - `auto` - show limits if they are in the yrange

With the default value `auto`.

Example:

```yaml
    plot:
      gain_vs_temp:
        type: xyplot
        xaxis: temperature
        yaxis: a0
        limits: true
      ugf_vs_corner:
        type: xyplot
        xaxis: corner
        yaxis: ugf
        limits: false
      pm_vs_vdd:
        type: xyplot
        xaxis: vdd
        yaxis: pm
        limits: auto
```

Would this work for you?
